const destinationOptions = [
    // Top 50 Indian Tourist Destinations
    { value: "Shimla", label: "Shimla" },
    { value: "Kerala", label: "Kerala" },
    { value: "Kashmir", label: "Kashmir" },
    { value: "Goa", label: "Goa" },
    { value: "Jaipur", label: "Jaipur" },
    { value: "Agra", label: "Agra" },
    { value: "Manali", label: "Manali" },
    { value: "Rishikesh", label: "Rishikesh" },
    { value: "Ooty", label: "Ooty" },
    { value: "Mysore", label: "Mysore" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Darjeeling", label: "Darjeeling" },
    { value: "Ladakh", label: "Ladakh" },
    { value: "Andaman and Nicobar Islands", label: "Andaman and Nicobar Islands" },
    { value: "Pondicherry", label: "Pondicherry" },
    { value: "Hampi", label: "Hampi" },
    { value: "Khajuraho", label: "Khajuraho" },
    { value: "Mahabalipuram", label: "Mahabalipuram" },
    { value: "Mumbai", label: "Mumbai" },
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Delhi", label: "Delhi" },
    { value: "Ranthambore", label: "Ranthambore" },
    { value: "Srinagar", label: "Srinagar" },
    { value: "Kanyakumari", label: "Kanyakumari" },
    { value: "Rajasthan Desert", label: "Rajasthan Desert" },
    { value: "Bangalore", label: "Bangalore" },
    { value: "Amritsar", label: "Amritsar" },
    { value: "Rann of Kutch", label: "Rann of Kutch" },
    { value: "Mount Abu", label: "Mount Abu" },
    { value: "Shillong", label: "Shillong" },
    { value: "Lonavala", label: "Lonavala" },
    { value: "Alleppey", label: "Alleppey" },
    { value: "Haridwar", label: "Haridwar" },
    { value: "Gangtok", label: "Gangtok" },
    { value: "Chennai", label: "Chennai" },
    { value: "Tirupati", label: "Tirupati" },
    { value: "Ajanta and Ellora", label: "Ajanta and Ellora" },
    { value: "Madurai", label: "Madurai" },
    { value: "Puri", label: "Puri" },
    { value: "Coorg", label: "Coorg" },
    { value: "Kochi", label: "Kochi" },
    { value: "Bodh Gaya", label: "Bodh Gaya" },
    { value: "Konark", label: "Konark" },
    { value: "Pushkar", label: "Pushkar" },
    { value: "Jaisalmer", label: "Jaisalmer" },
    { value: "Bikaner", label: "Bikaner" },
    { value: "Mahabaleshwar", label: "Mahabaleshwar" },

    // Top 50 International Tourist Destinations
    { value: 'France', label: 'France' },
    { value: 'Italy', label: 'Italy' },
    { value: 'UK', label: 'UK' },
    { value: 'USA', label: 'USA' },
    { value: 'UAE', label: 'UAE' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Japan', label: 'Japan' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Spain', label: 'Spain' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Germany', label: 'Germany' },
    { value: 'China', label: 'China' },
    { value: 'Greece', label: 'Greece' },
    { value: 'Czech Republic', label: 'Czech Republic' },
    { value: 'South Africa', label: 'South Africa' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Russia', label: 'Russia' },
    { value: 'Brazil', label: 'Brazil' },
    { value: 'Mexico', label: 'Mexico' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Iceland', label: 'Iceland' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'South Korea', label: 'South Korea' },
    { value: 'New Zealand', label: 'New Zealand' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Hungary', label: 'Hungary' },
    { value: 'Scotland', label: 'Scotland' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Ireland', label: 'Ireland' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Peru', label: 'Peru' },
];


export default destinationOptions